### ISSUE TITLE
Source no longer works.

### ISSUE THREAD

**Issue by TruBlaze** [sparkychild/ChuChuBoTTT#9]
As of last night [11/27/2015] your bot source has refused to work in any form whether it be running npm install or starting up the bot.

**Comment by sparkychild** [comment]
I think you've been seeing
TypeError: Cannot read property 'indexOf' of undefined
    at IncomingMessage.<anonymous> (/home/ubuntu/workspace/main.js:179:22)
    at emitOne (events.js:77:13)
    at IncomingMessage.emit (events.js:169:7)
    at IncomingMessage.Readable.read (_stream_readable.js:360:10)
    at flow (_stream_readable.js:743:26)
    at resume_ (_stream_readable.js:723:3)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)

which is an issue with showdown's server

i'll provide a quick fix to this

**Comment by TruBlaze** [comment]
Okay.

**Comment by AuraStormLucario** [comment]
yup ive seen this problem as well,

**Comment by sparkychild** [comment]
I've updated main.js so that using "override" is not needed anymore
